Add the termination checker to the pipeline
heliaxdev/minijuvix pull request #111
Opened 2022-05-16 23:48 UTC by jonaprieto

2022-05-19 22:29 UTC, jonaprieto commented
Blocked by #117

2022-05-30 11:07 UTC, janmasrovira requested changes
Some small comments

2022-05-30 11:07 UTC, janmasrovira commented on src/MiniJuvix/Pipeline/EntryPoint.hs
> +defaultEntryPoint mainFile = EntryPoint "." False (pure mainFile)
now that we are adding more fields, I think it makes sense to use record syntax with explicit fields

2022-05-30 11:35 UTC, janmasrovira approved these changes
🚢

2022-05-30 11:40 UTC, merged